const events = {
  login: "login",
  newUser: "newUser",
  sendMsg: "sendMsg",
  newMsg: "newMsg",
  beginPath: "beginPath",
  beganPth: "beganPth",
  strokePath: "strokePath",
  strokenPath: "strokenPath",
  fill: "fill",
  filled: "filled",
  erase: "erase",
  erased: "erased",
  setPencil: "setPencil",
  setPenciled: "setPenciled",
  addPlayer: "addPlayer",
  playerUpdate: "playerUpdate",
  disconnected: "disconnected",
  painterNotif: "painterNotif",
  gameStarted: "gameStarted",
  gameEnded: "gameEnded",
  disconnect: "disconnect",
  refresh: "refresh",
};

export default events;
